# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktopUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.connectionList = QtWidgets.QListWidget(self.centralwidget)
        self.connectionList.setObjectName("connectionList")
        self.gridLayout_3.addWidget(self.connectionList, 0, 1, 1, 1)
        self.chatWindow = QtWidgets.QListWidget(self.centralwidget)
        self.chatWindow.setObjectName("chatWindow")
        self.gridLayout_3.addWidget(self.chatWindow, 0, 2, 1, 3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_msg = QtWidgets.QWidget()
        self.tab_msg.setObjectName("tab_msg")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_msg)
        self.gridLayout.setObjectName("gridLayout")
        self.sendButton_0 = QtWidgets.QPushButton(self.tab_msg)
        self.sendButton_0.setObjectName("sendButton_0")
        self.gridLayout.addWidget(self.sendButton_0, 0, 1, 1, 1)
        self.messageEdit = QtWidgets.QLineEdit(self.tab_msg)
        self.messageEdit.setObjectName("messageEdit")
        self.gridLayout.addWidget(self.messageEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_msg, "")
        self.tab_file = QtWidgets.QWidget()
        self.tab_file.setObjectName("tab_file")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_file)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sendButton_1 = QtWidgets.QPushButton(self.tab_file)
        self.sendButton_1.setFlat(False)
        self.sendButton_1.setObjectName("sendButton_1")
        self.gridLayout_2.addWidget(self.sendButton_1, 1, 1, 1, 1)
        self.pickButton = QtWidgets.QPushButton(self.tab_file)
        self.pickButton.setObjectName("pickButton")
        self.gridLayout_2.addWidget(self.pickButton, 0, 1, 1, 1)
        self.pathEdit = QtWidgets.QLineEdit(self.tab_file)
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout_2.addWidget(self.pathEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_file, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 1, 1, 4)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 5)
        self.gridLayout_3.setRowStretch(0, 5)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect_To = QtWidgets.QAction(MainWindow)
        self.actionConnect_To.setObjectName("actionConnect_To")
        self.menuOptions.addAction(self.actionConnect_To)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sendButton_0.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_msg), _translate("MainWindow", "Tab 1"))
        self.sendButton_1.setText(_translate("MainWindow", "PushButton"))
        self.pickButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_file), _translate("MainWindow", "Tab 2"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionConnect_To.setText(_translate("MainWindow", "Connect To"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
