from PyQt5.QtWidgets import (QPushButton, QDialog, QLabel, QFormLayout, QLineEdit, QFileDialog, QSpinBox)
from peerconn import (PeerData)

class DialogListen(QDialog):
    def __init__(self, local_address: str) -> None:
        super().__init__()
        self.setWindowTitle('Create Listener')
        self.setMinimumSize(240, 200)
        self.setMaximumHeight(200)
        self.setWhatsThis('To create a listener/server.')
        layout = QFormLayout()
        self.QLineEdit_display_name = QLineEdit()
        layout.addRow(QLabel('Display Name'), self.QLineEdit_display_name)
        self.QLineEdit_local_address = QLineEdit(local_address)
        layout.addRow(QLabel('Address'), self.QLineEdit_local_address)
        self.QSpinBox_msg_port = QSpinBox()
        self.QSpinBox_msg_port.setMinimum(49152)
        self.QSpinBox_msg_port.setMaximum(65535 )
        layout.addRow(QLabel('Message Port'), self.QSpinBox_msg_port)
        self.QSpinBox_file_port = QSpinBox()
        self.QSpinBox_file_port.setMinimum(49152)
        self.QSpinBox_file_port.setMaximum(65535 )
        layout.addRow(QLabel('File Port'), self.QSpinBox_file_port)
        self.QPushButton_create_listener = QPushButton('Create')
        self.QPushButton_create_listener.clicked.connect(self.accept)
        layout.addRow(self.QPushButton_create_listener)
        self.QPushButton_cancel = QPushButton('Cancel')
        self.QPushButton_cancel.clicked.connect(self.reject)
        layout.addRow(self.QPushButton_cancel)
        self.setLayout(layout)

class DialogConnect(QDialog):
    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle('Create Connection')
        self.setMinimumSize(240, 200)
        self.setMaximumHeight(200)
        self.setWhatsThis('To connect a listener/server.')
        layout = QFormLayout()
        self.QLineEdit_display_name = QLineEdit()
        layout.addRow(QLabel('Display Name'), self.QLineEdit_display_name)
        self.QLineEdit_local_address = QLineEdit()
        layout.addRow(QLabel('Address'), self.QLineEdit_local_address)
        self.QSpinBox_msg_port = QSpinBox()
        self.QSpinBox_msg_port.setMinimum(49152)
        self.QSpinBox_msg_port.setMaximum(65535 )
        layout.addRow(QLabel('Message Port'), self.QSpinBox_msg_port)
        self.QSpinBox_file_port = QSpinBox()
        self.QSpinBox_file_port.setMinimum(49152)
        self.QSpinBox_file_port.setMaximum(65535 )
        layout.addRow(QLabel('File Port'), self.QSpinBox_file_port)
        self.QPushButton_create_listener = QPushButton('Connect')
        self.QPushButton_create_listener.clicked.connect(self.accept)
        layout.addRow(self.QPushButton_create_listener)
        self.QPushButton_cancel = QPushButton('Cancel')
        self.QPushButton_cancel.clicked.connect(self.reject)
        layout.addRow(self.QPushButton_cancel)
        self.setLayout(layout)

class DialogEditConnectionItem(QDialog):
    def __init__(self, peerdata: PeerData) -> None:
        super().__init__()
        # self.setWindowFlags(self.windowFlags() & ~Qt.WindowType.WindowCloseButtonHint)
        self.setWindowTitle(f'Edit {peerdata.name}')
        self.setMinimumSize(240, 200)
        self.setMaximumHeight(200)
        self.setWhatsThis('Here you can only edit name of the peersocket.')
        layout = QFormLayout()
        self.QLineEdit_display_name = QLineEdit(peerdata.name)
        layout.addRow(QLabel('Display Name'), self.QLineEdit_display_name)
        self.QLineEdit_local_address = QLineEdit(peerdata.local_address)
        self.QLineEdit_local_address.setReadOnly(True)
        layout.addRow(QLabel('Address'), self.QLineEdit_local_address)
        self.QLineEdit_msg_port = QLineEdit(str(peerdata.msg_port))
        self.QLineEdit_msg_port.setReadOnly(True)
        layout.addRow(QLabel('Message Port'), self.QLineEdit_msg_port)
        self.QLineEdit_file_port = QLineEdit(str(peerdata.file_port))
        self.QLineEdit_file_port.setReadOnly(True)
        layout.addRow(QLabel('File Port'), self.QLineEdit_file_port)
        self.QPushButton_save_changes = QPushButton('Save')
        self.QPushButton_save_changes.clicked.connect(self.accept)
        layout.addRow(self.QPushButton_save_changes)
        self.QPushButton_cancel = QPushButton('Cancel')
        self.QPushButton_cancel.clicked.connect(self.reject)
        layout.addRow(self.QPushButton_cancel)
        self.setLayout(layout)

class DialogChangeConfigs(QDialog):
    def __init__(self, peerdata: PeerData, download_dir_path: str) -> None:
        super().__init__()
        self.setWindowTitle(f'Edit Configurations')
        self.setMinimumSize(240, 200)
        self.setMaximumHeight(200)
        self.setWhatsThis('Here is your main configurations.'
                          'You can change and changes will be saved'
                          'except "Address".')
        layout = QFormLayout()
        self.QLineEdit_display_name = QLineEdit(peerdata.name)
        layout.addRow(QLabel('Host Name'), self.QLineEdit_display_name)
        self.QLineEdit_local_address = QLineEdit(peerdata.local_address)
        layout.addRow(QLabel('Address'), self.QLineEdit_local_address)
        self.QLineEdit_download_dir_path = QLineEdit(download_dir_path)
        layout.addRow(QLabel('Directory Path'), self.QLineEdit_download_dir_path)
        self.QPushButton_pick_dir = QPushButton('Pick Dir')
        def directory_dialog():
            directory_path = QFileDialog.getExistingDirectory(self, "Select Directory")
            if directory_path:
                self.QLineEdit_download_dir_path.setText(directory_path)
        self.QPushButton_pick_dir.clicked.connect(directory_dialog)
        layout.addRow(self.QPushButton_pick_dir)
        self.QPushButton_save_changes = QPushButton('Save')
        self.QPushButton_save_changes.clicked.connect(self.accept)
        layout.addRow(self.QPushButton_save_changes)
        self.QPushButton_cancel = QPushButton('Cancel')
        self.QPushButton_cancel.clicked.connect(self.reject)
        layout.addRow(self.QPushButton_cancel)
        self.setLayout(layout)